# Generated by Django 5.2.7 on 2026-10-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('TZS', 'Tanzanian Shilling (TZS)'), ('USD', 'US Dollar (USD)'), ('EUR', 'Euro (EUR)'), ('GBP', 'British Pound (GBP)'), ('KES', 'Kenyan Shilling (KES)'), ('UGX', 'Ugandan Shilling (UGX)'), ('NGN', 'Nigerian Naira (NGN)'), ('ZAR', 'South African Rand (ZAR)'), ('INR', 'Indian Rupee (INR)'), ('JPY', 'Japanese Yen (JPY)'), ('CNY', 'Chinese Yuan (CNY)'), ('CUSTOM', 'Custom — set your own symbol')], default='TZS', help_text='Currency used everywhere in the system.', max_length=10)),
                ('symbol_override', models.CharField(blank=True, help_text='Optional. Replaces the currency symbol above, e.g. "TSh", "FCFA", "د.إ".', max_length=8)),
                ('symbol_position', models.CharField(choices=[('auto', 'Automatic'), ('before', 'Before the amount  (e.g. $1,234.56)'), ('after', 'After the amount  (e.g. 1,234.56 $)')], default='auto', max_length=6)),
                ('decimal_places', models.CharField(choices=[('auto', 'Automatic (as per currency)'), ('0', '0 decimals  (1,234)'), ('1', '1 decimal   (1,234.5)'), ('2', '2 decimals  (1,234.56)'), ('3', '3 decimals  (1,234.567)'), ('4', '4 decimals  (1,234.5678)')], default='auto', max_length=4)),
                ('thousands_separator', models.CharField(choices=[('auto', 'Automatic (as per currency)'), ('comma', 'Comma  — 1,000,000'), ('dot', 'Dot  — 1.000.000'), ('space', 'Space  — 1 000 000'), ('none', 'None  — 1000000')], default='auto', max_length=5)),
                ('decimal_separator', models.CharField(choices=[('auto', 'Automatic (as per currency)'), ('dot', 'Dot  — 1,000.00'), ('comma', 'Comma  — 1.000,00')], default='auto', max_length=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
