# Generated by Django 5.2.7 on 2025-10-23 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_supplier_address_supplier_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='stockmovement',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
