# Generated by Django 5.2.7 on 2025-12-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_stockmovement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='profit_margin_display',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
