# Generated by Django 5.2.7 on 2026-10-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_stockmovement_movement_type_supplierreturn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Optional. When purchasing this order the product expiry is set from this date.', null=True),
        ),
    ]
