# Generated by Django 5.2.7 on 2026-10-02 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_purchaseorderitem_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='expiry_date',
        ),
    ]
