# Generated by Django 5.2.7 on 2026-10-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_product_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Optional. The use-by date printed on this delivery — the shelf life the shop reports for this product.', null=True),
        ),
    ]
