# Generated by Django 5.2.7 on 2025-10-25 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wasterecord',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='wasterecord',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
