# Generated by Django 5.2.7 on 2025-10-23 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-created_by']},
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='timestamp',
            new_name='created_by',
        ),
    ]
