# Generated by Django 5.2.7 on 2025-10-23 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_sale_options_rename_timestamp_sale_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='created_by',
            new_name='created_at',
        ),
    ]
